server:
  port: 8080

cors:
  allowed:
    origins: http://library.productdock.rs

spring:
  kafka:
    enabled: true
    bootstrap-servers: ${kafka.server.url:9092}
    value-seriliazer: org.apache.kafka.common.serialization.StringSerializer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      enable-auto-commit: true
      auto-offset-reset: latest
      group-id: ${consumer.group:group}
    topic:
      insert-book: ${kafka.topic.insert-book:insert-book}
      book-status: ${kafka.topic.book-status:book-status}
      book-availability: ${kafka.topic.book-availability:book-availability}
      book-rating: ${kafka.topic.book-rating:book-rating}
  elasticsearch:
    rest:
      uris: ${elasticsearch.server.url}:9200