spring:
  kafka:
    enabled: true
    bootstrap-servers: ${kafka.server.url:localhost:9092}
    value-seriliazer: org.apache.kafka.common.serialization.StringSerializer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      insert-book: insert-book
      book-status: book-status
      book-availability: book-availability
      book-rating: book-rating
      book-recommendation: book-recommendation
  elasticsearch:
    rest:
      uris: ${elasticsearch.server.url:localhost}:9200

kafka-consumer-factory:
  auto-offset-reset: latest
  group-id: rbc-library-search
